upload already done hw1
proevgenii/EPAM-HW-2020- pull request #1
Opened 2021-03-05 20:43 UTC by proevgenii

2021-03-07 12:57 UTC, PeppaTheC requested changes

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/requirements.txt
> +isort
почему где-то версии зафиксированы, а где-то нет?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task02.py
> +    8,
в чем смысл такой длинной последовательности?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task02.py
> +        # print(len(data), data[2])
закоменченный код, в репо лучше не пушить

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task02.py
> +        data = data[1:]
можно, сделать гораздо проще - не делая слайс каждый раз. Попробуй переписать с циклом for и без слайсинга

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/requirements.txt
> +black==20.8b1
почему requirements лежит в папке hw1?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task03.py
> +        for line in fi:
"We guarantee, that file exists and contains line-delimited integers." - как-то не вяжется решение с этим условием

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task03.py
> +            min_max_list.append(min(line))
зачем на каждой итерации искать мин и макс?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task03.py
> +            line = [int(i) for i in line.strip("\n").split()]
предполагается что файл выглядит вот так
1\n
2\n
3\n

`line.strip("\n")` очень странно использовать вместе с `for line in fi:`

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task04.py
> +    sums_1 = {}
что значит _1 в названии переменной?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task05.py
> +    assert len(nums) > k
можно ли использовать assert вне тестов?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task05.py
>  def find_maximal_subarray_sum(nums: List[int], k: int) -> int:
какая-то неоправданная сложность решения

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task05.py
>  def find_maximal_subarray_sum(nums: List[int], k: int) -> int:
зачем тут рекурсия? и чем это плохо?

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/tests/test_for_task02.py
> +            [
я думаю длину тестовых данных можно сократить

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/test.txt
> +1 2 3 4
формат файла неправильный
и я бы поменял название на fixture_data_1.txt

2021-03-07 12:57 UTC, PeppaTheC commented on hw1/task05.py
> +nums = [1, 3, -1, -3, 5, 3, 6, 7]
зачем тут эти переменные?

2021-03-07 13:04 UTC, proevgenii commented on hw1/requirements.txt
> +isort
Потому что именно такие requirements лежат в репозитории epam

2021-03-07 13:05 UTC, proevgenii commented on hw1/task02.py
> +    8,
black таким образом отформатировал

2021-03-07 13:06 UTC, PeppaTheC commented on hw1/requirements.txt
> +isort
Надо видимо там тоже поправить

2021-03-07 13:07 UTC, PeppaTheC commented on hw1/task02.py
> +    8,
вопрос был в количествен данных

2021-03-07 13:07 UTC, PeppaTheC commented on hw1/task02.py
> +    8,
вопрос был про количество данных в массиве

2021-03-07 13:08 UTC, proevgenii commented on hw1/requirements.txt
> +black==20.8b1
А где он должен лежать ?  Это же для всей hw1 только

2021-03-07 13:10 UTC, proevgenii commented on hw1/task03.py
> +        for line in fi:
Ниже в задании :
"""To read file line-by-line you can use this snippet:
with open("some_file.txt") as fi:
    for line in fi:"""

2021-03-07 13:11 UTC, PeppaTheC commented on hw1/requirements.txt
> +black==20.8b1
Нелогично в одном репо хранить зависимости в разных папках, если учесть что они все для python. Так же придется в придется итерироваться по папками и ставить все зависимости по очереди.

2021-03-07 13:12 UTC, PeppaTheC commented on hw1/task03.py
> +        for line in fi:
Эта часть конкретно правильная, а дальнейшие реализация нет.

2021-03-07 13:16 UTC, proevgenii commented on hw1/task03.py
> +            min_max_list.append(min(line))
Если я правильно понимаю смысл кода :
 **with open(file_name) as fi:
        for line in fi:**
То одна итерация это одна строка в файле и соответсвенно ищу минимум и максимум в каждой строке

2021-03-07 13:20 UTC, PeppaTheC commented on hw1/task03.py
> +            min_max_list.append(min(line))
```
 with open(file_name) as fi:
    for line in fi:
```
Одна итерация одна строка. Одна строка - одно число. => contains line-delimited integers

2021-03-10 11:39 UTC, PeppaTheC requested changes

2021-03-10 11:39 UTC, PeppaTheC commented on hw1/requirements.txt
> +black==20.8b1
Нужно перенести в корень

2021-03-10 11:39 UTC, PeppaTheC commented on hw1/task02.py
> +    b = data[1::3]
зачем тут слайс, можно взять по индексу

2021-03-10 11:39 UTC, PeppaTheC commented on hw1/task03.py
> +        file = [int(char) for line in fi for char in line.split()]
файл имеет другой вид, сплит не нужен

2021-03-10 11:39 UTC, PeppaTheC commented on hw1/task02.py
> +            return True
решение точно правильно?

2021-04-01 18:19 UTC, PeppaTheC approved these changes

2021-04-14 16:48 UTC, merged