Doing hw2
proevgenii/EPAM-HW-2020- pull request #3
Opened 2021-03-10 14:42 UTC by proevgenii

2021-03-17 17:48 UTC, PeppaTheC requested changes

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +            [word for line in fi for word in re.findall(r"\w+", line)],
что насчет слов разделенных - или содержащих '

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +        for char in fi.read().strip("\n").strip():
зачем тут два strip("\n").strip()

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +    punc = set(r"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~""")
лучше сделать extend для string.punctuation

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +    """
что за странный комментарий?

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +    non_ascii_char = sum(char.isascii() is False for char in file_text)
nice

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +                    pass
что делает эта строчка?

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw1.py
> +    >>> count_punctuation_chars('file.txt')
окей, либо писать хороший коммент с док тестами или не писать комменты вообще лучше

можешь посмотреть https://google.github.io/styleguide/pyguide.html

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/tests_hw2/test_for_get_longest_diverse_word.py
> +file = open("test.txt", "w")
это вынести в pytest fixture https://docs.pytest.org/en/stable/fixture.html#back-to-fixtures

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/tests_hw2/test_for_get_longest_diverse_word.py
> +import pytest
тестов мало, и не покрыты все функции

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw5.py
> +        outp.append(rule[elem])
упрости через  [some_list][start:stop:step]

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw2.py
> +    return maj_min
неправильная аннотация типов получается

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw2.py
> +    conter = Counter(inp)
если используешь Counter тогда и используй метод most_common

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw3.py
> +print(combinations_lists([1, 2], [3, 4]))
надо убрать из кода

2021-03-17 17:48 UTC, PeppaTheC commented on hw2/hw4.py
> +    return cache
что это?

2021-03-20 20:00 UTC, proevgenii commented on hw2/hw5.py
> +        outp.append(rule[elem])
Точно!

2021-03-20 20:00 UTC, proevgenii commented on hw2/hw4.py
> +    return cache
недостижимый кусок кода с лишним return, поправил

2021-03-20 20:00 UTC, proevgenii commented on hw2/hw3.py
> +print(combinations_lists([1, 2], [3, 4]))
Исправил

2021-03-20 20:00 UTC, proevgenii commented on hw2/hw2.py
> +    return maj_min
Исправил

2021-03-20 20:03 UTC, proevgenii commented on hw2/hw1.py
> +                    pass
Лишний код, ничего не делает, исправил

2021-03-20 20:03 UTC, proevgenii commented on hw2/hw1.py
> +    punc = set(r"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~""")
Сделал

2021-03-20 20:04 UTC, proevgenii commented on hw2/hw1.py
> +        for char in fi.read().strip("\n").strip():
Ошибка, исправил

2021-03-20 20:05 UTC, proevgenii commented on hw2/hw1.py
> +    """
Я так пытался писать доктесты, если я правильно понимаю, то ошибка этих доктестов в том что они не информативные,  т.е не понятно как получается результат ?

2021-03-20 20:10 UTC, proevgenii commented on hw2/hw1.py
> +            [word for line in fi for word in re.findall(r"\w+", line)],
Исправил

2021-04-01 18:03 UTC, PeppaTheC requested changes

2021-04-01 18:03 UTC, PeppaTheC commented on hw2/hw1.py
> +    >>> get_most_common_non_ascii_char('file.txt')
убери неинформативные комментарии

2021-04-01 18:03 UTC, PeppaTheC commented on hw2/tests_hw2/test_for_get_longest_diverse_word.py
> +    file = open("test.txt", "w")
используй контекстный менеджер

2021-04-01 18:03 UTC, PeppaTheC commented on hw2/hw1.py
> +    """
да комментарии не несут никакого смысла

2021-04-01 18:03 UTC, PeppaTheC commented on hw2/hw4.py
> +        key = args + tuple(sorted(kwargs.items()))
получу ли я одинаковый результат если 
```
@cache
def func(a: int = 1) -> int:
    return a


func()
func(1)
func(a=1)
```

2021-04-01 18:03 UTC, PeppaTheC commented on hw2/tests_hw2/test_for_function_cacher.py
> +def test_function_has_called(m, n, number_of_calls):
эти тесты все случаи проверяют?

2021-04-01 18:21 UTC, PeppaTheC approved these changes

2021-04-14 16:48 UTC, merged