Doing hw3
proevgenii/EPAM-HW-2020- pull request #4
Opened 2021-03-13 21:54 UTC by proevgenii

Совсем не уверен в корректности тестов для декоратора и для вычисления суммы с помощью модуля multiprocessing

2021-03-17 18:13 UTC, PeppaTheC requested changes

2021-03-17 18:13 UTC, PeppaTheC commented on hw3/task02/task02.py
> +    if __name__ == "__main__":
?

2021-03-17 18:13 UTC, PeppaTheC commented on hw3/task02/task02.py
> +        with Pool(28) as p:
почему 28 и что это значит?

2021-03-17 18:13 UTC, PeppaTheC commented on hw3/task01/task01.py
> +        def decorator(*args):
что насчет **kwargs

2021-03-17 18:13 UTC, PeppaTheC commented on hw3/task03/task03.py
> +            return value[key] == values
make_filter(name='polly', type='bird', kind='test').apply(sample_data)

2021-03-17 18:13 UTC, PeppaTheC commented on hw3/task04/test_for_func_is_armstrong.py
> +    assert is_armstrong(153) is True, "Is Armstrong number"
parametrize

2021-03-21 16:40 UTC, proevgenii commented on hw3/task02/task02.py
> +        with Pool(28) as p:
Это число процессов, минимальное с которым на моем устройстве вычисление занимает меньше минуты

2021-03-21 16:40 UTC, proevgenii commented on hw3/task02/task02.py
> +    if __name__ == "__main__":
Не знаю как по другому оформить чтобы было возможно тестировать, ведь изначально заданную функцию нельзя изменять

2021-03-21 16:43 UTC, proevgenii commented on hw3/task01/task01.py
> +        def decorator(*args):
без проблем можно добавить **kwargs, но в задании была функция которая принимает лишь один аргумент и его и возвращает поэтому сделал только *args

2021-03-21 17:42 UTC, proevgenii commented on hw3/task03/task03.py
> +            return value[key] == values
Такое должно вернуть None, но в данном случае будет ошибка т.к в одном из словарей sample data нету такого ключа"kind", для этого надо добавить проверку на существование ключа, если я правильно понимаю

2021-04-01 18:19 UTC, PeppaTheC requested changes

2021-04-01 18:19 UTC, PeppaTheC commented on hw3/task01/task01.py
> +def timer(times):
```
 @cache(times=2)
    def f():
        return input('? ')
```
works?

2021-04-01 18:19 UTC, PeppaTheC commented on hw3/task01/task01.py
> +        def decorator(*args):
можно и без

2021-04-01 18:19 UTC, PeppaTheC commented on hw3/task02/task02.py
> +    with Pool(28) as p:
что за магическое число 28?

2021-04-01 18:19 UTC, PeppaTheC commented on hw3/task03/task03.py
> +        print(key, values, keywords.items())
принт в продакшене!

2021-04-01 18:19 UTC, PeppaTheC commented on hw3/task03/task03.py
> +            else: return None
PEP8 не так завещал

2021-04-01 18:22 UTC, PeppaTheC commented on hw3/task02/task02.py
> +        with Pool(28) as p:
как его рассчитать?

2021-04-01 18:22 UTC, PeppaTheC approved these changes

2021-04-14 16:48 UTC, merged