ulpload already done hw4
proevgenii/EPAM-HW-2020- pull request #5
Opened 2021-03-15 18:01 UTC by proevgenii

2021-03-17 18:21 UTC, PeppaTheC requested changes

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/task_1_read_file.py
> +                raise ValueError(
точно по логике нужно ValueError raise делать?

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/task_1_read_file.py
> +                first_line = float(fi.readline())
isinstance лучше использовать

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/task_2_mock_input.py
> +        for line in response:
response.read().decode('utf-8').count('i')

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
я думаю нужно несколько разных ошибок отработать
ValueError это странно

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/task_3_get_print_output.py
> +    result = re.findall(r"^\w+", text)  # get only first word
проще без re.findall(r"^\w+", text) лучше использовать str.startswith

2021-03-17 18:21 UTC, PeppaTheC commented on hw4/tests/test_correct_path_for_func_read_number.py
> +    with pytest.raises(IOError):
эта ошибка не покрыта логикой твоего приложения, у тебя только ValueError

2021-03-21 18:26 UTC, proevgenii commented on hw4/task_1_read_file.py
> +                raise ValueError(
"In case of any error, a ValueError should be thrown. " Это  задание

2021-03-21 19:15 UTC, proevgenii commented on hw4/task_1_read_file.py
> +                first_line = float(fi.readline())
чтобы проверить существует ли файл ? Или чтобы прочитать первую строку ? или для чего

2021-03-21 19:17 UTC, proevgenii commented on hw4/task_2_mock_input.py
> +        for line in response:
Исправил, но насколько хорошо использовать read() ведь есть страница будет супер огромной то мы прочитаем большой объем в оперативку и всё может повиснуть ? или я ошибаюсь

2021-03-21 19:30 UTC, proevgenii commented on hw4/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
"In case of any network error raise ValueError("Unreachable {url}) " Это опять же задание. А какие еще ошибки нужно обработать ?

2021-03-21 19:33 UTC, proevgenii commented on hw4/task_1_read_file.py
> +        raise IOError("File not accessible")
Вот еще ошибка если путь не правильный

2021-03-21 19:36 UTC, proevgenii commented on hw4/tests/test_correct_path_for_func_read_number.py
> +    with pytest.raises(IOError):
Может я не понимаю, но вроде как 47,48 строки в task_1_read_file.py

2021-04-01 18:24 UTC, PeppaTheC approved these changes

2021-04-01 18:24 UTC, PeppaTheC commented on hw4/task_1_read_file.py
> +                first_line = float(fi.readline())
что делает вот это преобразование? float

2021-04-01 18:24 UTC, PeppaTheC commented on hw4/task_1_read_file.py
> +                raise ValueError(
ммм, как интересно.  Надо поправить видимо задание. Но на будущие всегда лучше возвращать значимые ошибки.

2021-04-01 18:24 UTC, PeppaTheC commented on hw4/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
пусть будет так

2021-04-01 18:24 UTC, PeppaTheC commented on hw4/tests/test_correct_path_for_func_read_number.py
> +    with pytest.raises(IOError):
да просмотрел

2021-04-01 18:52 UTC, PeppaTheC commented on hw4/task_2_mock_input.py
> +        for line in response:
нет, все правильно. Лучше построчно обрабатывать, это для примера

2021-04-14 16:49 UTC, merged